# Generated by Django 4.2.4 on 2023-08-14 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_fanlar_yunalishlar_unversitetlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unversitetlar',
            name='yunalishlar',
        ),
        migrations.RemoveField(
            model_name='yunalishlar',
            name='fanlar',
        ),
        migrations.AddField(
            model_name='fanlar',
            name='yunalish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_api.yunalishlar'),
        ),
        migrations.AddField(
            model_name='yunalishlar',
            name='unversitet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_api.unversitetlar'),
        ),
    ]
